### ISSUE TITLE
vcffilter can't accept VCF files

### ISSUE THREAD

**Issue by bgruening** [nekrut/vcflib-tools#1]
Hi @nekrut,

is there any reason vcffilter does not accept any regular vcf file? Would you accept patches to also support VCF? Any plan to add the other filter parameters?

Thanks,
Bjoern

**Comment by nekrut** [comment]
yes, I would certainly accept patches.

**Comment by nekrut** [comment]
It accepts tabixed version of vcf in case filtering needs to be performed on coordinate. Since tabix is distributed as one of the eggs it should not be an issues. I'm just about to release a version of vcflibtools, which is based on the latest vcflib release

**Comment by bgruening** [comment]
Thanks @nekrut. Will test it ...
